### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by nisshi-dev** [jphacks/F_2109_1_frontCoder_Client#42]
## ページ

- サインイン
/signin
- ユーザー情報編集
/user/profile
- 問題一覧
/problem
- 問題詳細画面
/problem/:problemId

**Comment by HosokawaR** [comment]
細かい話で恐縮ですが、`/problem/:broadcastId` の `broadcast` とはなんでしょうか？

**Comment by nisshi-dev** [comment]
@HosokawaR 
済みません、誤植です🙇‍♂️
修正しました。

**Comment by HosokawaR** [comment]
了解です！

**Comment by Tanesan** [comment]
@HosokawaR これをURL設計の実装という形でslackの通り細川氏をassignしました.
URLの情報はwikiにあると思います.
