### ISSUE TITLE
ターミナル環境の導入の検討

### ISSUE THREAD

**Issue by kenkenpa2126** [jphacks/F_2109_1_frontCoder_Client#5]
* できそうか
* できたとして、やるべきか

のメドをつけたい

**Comment by nisshi-dev** [comment]
ターミナルはXterm.jsで良さそう
https://github.com/xtermjs/xterm.js/

websocketと組み合わせればawsインスタンスにアクセスしてターミナルで表示、みたいなことできそう

P.S. 
ターミナルでのポートフォリオサイト格好いい
https://kazuyan-cui.vercel.app/

**Comment by nisshi-dev** [comment]
htmlプレビューはターミナル環境なくても実装できそう。

react周りはこれ使えばいけそう
https://github.com/FormidableLabs/react-live

**Comment by mox692** [comment]
> websocketと組み合わせればawsインスタンスにアクセスしてターミナルで表示、みたいなことできそう

めっちゃ面白そうですよね！！！
自分もちょうど似た様な部分を調べてました↓

* https://developpaper.com/go-language-xterm-js-websocket-web-terminal-fortress/
* https://joeir.medium.com/setting-up-a-go-backend-for-xterm-js-to-get-a-shell-over-the-browser-508e3be3fb4d
* https://qiita.com/hrkt/items/58fc44173ab97790fbfc

明日の夜とか少し時間使ってこの辺り試してみてもう少し情報得ようと思います！
