### ISSUE TITLE
問題詳細画面作成

### ISSUE THREAD

**Issue by nisshi-dev** [jphacks/F_2109_1_frontCoder_Client#51]

**Comment by HosokawaR** [comment]
必要な要素は以下で十分でしょうか。他に追加したほうがいい項目とかありますか。
また、問題のプレビューを見せるのはありでしょうか、なしでしょうか。


![image](https://user-images.githubusercontent.com/45098934/139165031-fd4d3328-366d-482f-afcf-f3460d8f3949.png)


https://www.figma.com/file/4hV773wtHNQx0swpq2gNdH/UI%2FUX?node-id=45%3A55

**Comment by Tanesan** [comment]
ヘッダー(とかフッター)ってタスク化なかったけど結局そういうところってだれがするんですか？

**Comment by nisshi-dev** [comment]
@Tanesan 
ヘッダーはとりあえず仮のものを僕の方で作成してますので、昼頃にマージして共有します！

**Comment by nisshi-dev** [comment]
@HosokawaR 
ありがとうございます！
要素としては、追加で説明文も欲しいので、そこをタイトルの下とかのスペースに追加お願いします！！

プレビューはありです！
ありがとうございます！

**Comment by HosokawaR** [comment]
OKです！ありがとうございます！
